### ISSUE TITLE
Join this repository with symfony-bundle

### ISSUE THREAD

**Issue by jkobus** [php-translation/symfony-storage#10]
It will make work and bugfixing with the bundle easier.

**Comment by Nyholm** [comment]
I've been back and forth on this. You want them in the same repo or the same package?

**Comment by jkobus** [comment]
The same repo and the package.

Current disadventages:
- bundle is hard to maintain (versioning multiple packages, one small change in one repository will make a chain reaction on the others)
- bundle is harder to understand
- closely related issues are spread across repositories (i could not find reported issue; i forgot the repo it was in :))

I would keep most of the things together unless there would be a really good reason to not to do so.

**Comment by Nyholm** [comment]
Like I said, I've been back and forth. 

Some [other packages](https://packagist.org/packages/php-translation/symfony-storage/dependents) has a dependency on the SymfonyStorage. It does not seam fair that they should have a dependency for the complete bundle. 

The SymfonyStorage also works as a BC bridge to different Symfony versions.
