### ISSUE TITLE
FileStorage output format not configurable

### ISSUE THREAD

**Issue by Guite** [php-translation/symfony-storage#48]
The `FileStorage` class uses a configuration setting `default_output_format` which is not defined anywhere else. Hence, it always falls back to the default value `xlf`.

**Comment by odolbeau** [comment]
Hi @Guite 
What do you mean by "not defined anywhere else"?

This option is used to choose the format which will be passed to the translation writer:
https://github.com/php-translation/symfony-storage/blob/master/src/FileStorage.php#L158-L159

If you're using the symfony bundle, you can override this format from your configuration: https://github.com/php-translation/symfony-bundle/issues/302#issuecomment-572112657

**Comment by Guite** [comment]
The configured `output_format` is not used there. If I try to define `default_output_format: yaml` in addition I receive this error:
```
Unrecognized option "default_output_format" under "translation.configs.myconfig".
```

Shouldn't https://github.com/php-translation/symfony-storage/blob/master/src/FileStorage.php#L158-L159 use `output_format` instead of `default_output_format` then?

**Comment by odolbeau** [comment]
I took a look at the bundle configuration.

If you want to be sure to export your config in another format you can use:

```yaml
translation:
    configs:
        app:
            output_format: "po"
            local_file_storage_options:
                default_output_format: "po"
```

The `output_format` is needed when using `translation:download` command: it will be used to configure the `TranslationWriter` directly as we don't use a `LocalStorage` at this point.
The `default_output_format` under `local_file_storage_options` will be used to configure your local storage when using the `translation:sync` command for example.

This is this second option which will be injected in the `FileStorage` constructor argument.

**Comment by Guite** [comment]
Works like a charm! Thank you very much.
