### ISSUE TITLE
File format options for the XliffFileDumper

### ISSUE THREAD

**Issue by Spomsoree** [php-translation/symfony-storage#62]
I'm not sure if this is a feature request or if I'm just unable to find the documentation.
I want to increase the indent of our translation files if a missing translation is automatically added.

This is my configuration:
```
translation:
    locales:        '%locales_array%'
    default_locale: '%locale%'
    webui:
        enabled: true
    edit_in_place:
        enabled:     false
        config_name: site
    configs:
        site:
            dirs: [ "%kernel.project_dir%/public/theme/%bolt.theme%" ]
            output_dir: "%kernel.project_dir%/translations"
            local_file_storage_options: [ ]
    auto_add_missing_translations:
        enabled:     true
        config_name: site
```

I think this might be already possible through `local_file_storage_options`, but I'm not able to find any documentation on this.

**Comment by bocharsky-bw** [comment]
Hm, IIRC we use 4 spaces for indentation, right? Do you want to increase the indentation like to 8 spaces? I just wonder about your use case. But IIRC it's not possible to change via configuration for now

**Comment by Spomsoree** [comment]
My `.xlf` files use 2 space indent. I want to have 4.

I'm using this in a symfony 5 project and I'm not aware of any changed I made regarding this topic.
If I can provide any further info on this, let me know.

I'm now using my xml linter to fix this for me.

**Comment by welcoMattic** [comment]
If an XML linter does the job, let's close this one.
